### ISSUE TITLE
Chrome extension 404s

### ISSUE THREAD

**Issue by KetchupBomb** [hukoeth/polrchrome#1]
Hi @hukoeth,

I am considering self-hosted URL shorteners and Polr is an option. It would be great to have a Chrome integration so I can create URLs with a single click.

Is this project deprecated?

**Comment by LouisHacking** [comment]
@hukoeth This chrome extension still works with polr.

**Comment by hukoeth** [comment]
I stopped using Polr as it seemed unmaintained so I can't speak to if it still works. I'm happy to merge any pull requests if you like to bring it up to snuff. Also feel free forking if you want.
